// ─── Central Screen Route Names ───────────────────────────────────────────────

export type Screen =
  | "splash"
  | "login"
  | "home"
  | "all-categories"
  | "browse"
  | "provider-profile"
  | "booking"
  | "booking-success"
  | "tracking"
  | "conversations"
  | "messaging"
  | "review"
  | "bookings"
  | "booking-completed"
  | "user-profile"
  | "favorites"
  | "saved-addresses"
  | "payment-methods"
  | "notifications-settings"
  | "privacy-security"
  | "account-status"
  | "help-support"
  | "chatbot"
  | "terms-conditions"
  | "privacy-policy"
  | "provider-terms"
  | "provider-apply"
  | "provider-apply-status"
  | "provider-dashboard"
  | "provider-availability"
  | "provider-booking-request"
  | "provider-reviews"
  | "provider-services";
